### ISSUE TITLE
m3u link

### ISSUE THREAD

**Issue by samivictor** [zhangboheng/Easy-Web-TV-M3u8#1]
hi
Hi,
how hide the link .m3u8 from the menu
<img width="731" alt="menu" src="https://user-images.githubusercontent.com/85029093/122996236-eb44fc80-d3aa-11eb-9862-13b1543bf891.png">

**Comment by zhangboheng** [comment]
Hey, you can edit "<p title=" + links[i] + ">" to "<p class=" + links[i] + ">", then change src: $(this).attr("title") to src: $(this).attr("class") in main.js.

**Comment by samivictor** [comment]
thank you its work god for google chrome not microsoft edge
