### ISSUE TITLE
 direct link

### ISSUE THREAD

**Issue by samivictor** [zhangboheng/Easy-Web-TV-M3u8#2]
direct link

How can I add a direct link?
in main.js like 
https://iptv-org.github.io/iptv/countries/dk.m3u
https://list.iptvcat.com/my_list/289a7cba590b543a3d79af04a6e2c399.m3u8

its can only add Playlists by category
can you help

**Comment by zhangboheng** [comment]
Now, you can select countries, languages, or categories.

**Comment by samivictor** [comment]
thanks
