### ISSUE TITLE
list loading not work using mobile

### ISSUE THREAD

**Issue by heryartshtv** [zhangboheng/Easy-Web-TV-M3u8#3]
a very good script, but after I tried to use my phone, it turned out that the load list didn't open and it was always stuck on the Channel list is loading...

how to fix it :)

**Comment by zhangboheng** [comment]
Oh, buddy, I guess the channel lists cannot be loaded in some countries or regions. Some countries and regions have blocked IPTV-org links. I recommend using VPN to watch

**Comment by zhangboheng** [comment]
I have fixed it.
